#!/bin/bash

# source the ciop functions (e.g. ciop-log, ciop-getparam)
source ${ciop_job_include}

node="satcen-mtc"

source /application/${node}/lib/functions.sh

trap cleanExit EXIT

cat | main || exit $?
